### ISSUE TITLE
Not letting me add renderer feature on URP.

### ISSUE THREAD

**Issue by ccvetkovski** [keijiro/KinoAqua#4]
I followed all of the instructions for installation on URP and when I have to add a renderer feature, it is simply not showing up as an option.

**Comment by keijiro** [comment]
How about the Aqua Effect component? Is it showing up on the Add Component menu?

**Comment by ccvetkovski** [comment]
No, it is not showing up on the Add Component menu. I tried adding the Aqua Effect component to the camera.

**Comment by keijiro** [comment]
It seems the package import may have failed. Is KinoAqua listed in the Package Manager’s package list?

**Comment by ccvetkovski** [comment]
Yes, KinoAqua does show up on the Package Manager list.

**Comment by keijiro** [comment]
How about the "KinoAqua (URP)" package? You need to import it along with the base KinoAqua package.

**Comment by ccvetkovski** [comment]
Where would I install that?

**Comment by keijiro** [comment]
The package should appear in the list, but due to an unknown issue, it might not show up. If that’s the case, you can try using the ‘Install package by name’ method with `jp.keijiro.kino.aqua.universal`.

**Comment by ccvetkovski** [comment]
Thank you! It works. :)
